### ISSUE TITLE
GET /org/{orgId}/teams/{objectId} always errors?

### ISSUE THREAD

**Issue by ijxy** [vleipnik-consensys/tmnt-client#18]
Hi Sobol team, I've been using the JS and for the most part it is great -- very simple and descriptive.

However, I've been having an issue trying to get a specific team by ID, even using the web-interface.

If we get all teams, and take the `_id` of the first one, seen below to be `rk2MHeCBu-G`, then try to query for that team specifically, it throws an error about a missing parameter `objectId`. (Screenshots below).

Looking through the `base/index.js` file in this repo I'm inclined to suspect that it's because there is actually no `client.Teams.findById` function, only the `client.Teams.find` function that returns *all* teams.

Please let me know if I'm doing something wrong or whether this is just not implemented yet. If the latter, it might be worth noting it as such on the Swagger UI page.

Thanks!

![image](https://user-images.githubusercontent.com/32483798/61002291-27ffc080-a359-11e9-8a5e-bf99962ef06e.png)

![image](https://user-images.githubusercontent.com/32483798/61002459-7b720e80-a359-11e9-871d-66fd25125b76.png)

![image](https://user-images.githubusercontent.com/32483798/61002947-9e50f280-a35a-11e9-9053-602640bd34ac.png)

**Comment by vleipnik** [comment]
@parkinsonj this has been fixed and released tonight - thank you for reporting!
